# -*- coding: utf-8 -*-
site_config = {
    "indeed_co_in": {
        "domain": "www.indeed.co.in",
        "method": "GET",
        "allowed_domains": ['indeed.co.in'],
        "parsing_type": "xpath",
        "category": {
            "start_urls": ["https://www.indeed.co.in/jobs?q=&l=Andhra+Pradesh",
                           "https://www.indeed.co.in/jobs?q=&l=Arunachal+Pradesh",
                           "https://www.indeed.co.in/jobs?q=&l=Assam",
                           "https://www.indeed.co.in/jobs?q=&l=Bihar",
                           "https://www.indeed.co.in/jobs?q=&l=Chhattisgarh",
                           "https://www.indeed.co.in/jobs?q=&l=Goa",
                           "https://www.indeed.co.in/jobs?q=&l=Gujarat",
                           "https://www.indeed.co.in/jobs?q=&l=Haryana",
                           "https://www.indeed.co.in/jobs?q=&l=Himachal+Pradesh",
                           "https://www.indeed.co.in/jobs?q=&l=Jammu+and+Kashmir",
                           "https://www.indeed.co.in/jobs?q=&l=Jharkhand",
                           "https://www.indeed.co.in/jobs?q=&l=Karnataka",
                           "https://www.indeed.co.in/jobs?q=&l=Kerala",
                           "https://www.indeed.co.in/jobs?q=&l=Madhya+Pradesh",
                           "https://www.indeed.co.in/jobs?q=&l=Maharashtra",
                           "https://www.indeed.co.in/jobs?q=&l=Manipur",
                           "https://www.indeed.co.in/jobs?q=&l=Meghalaya",
                           "https://www.indeed.co.in/jobs?q=&l=Mizoram",
                           "https://www.indeed.co.in/jobs?q=&l=Nagaland",
                           "https://www.indeed.co.in/jobs?q=&l=Orissa",
                           "https://www.indeed.co.in/jobs?q=&l=Punjab",
                           "https://www.indeed.co.in/jobs?q=&l=Rajasthan",
                           "https://www.indeed.co.in/jobs?q=&l=Sikkim",
                           "https://www.indeed.co.in/jobs?q=&l=Tamil+Nadu",
                           "https://www.indeed.co.in/jobs?q=&l=Telangana",
                           "https://www.indeed.co.in/jobs?q=&l=Tripura",
                           "https://www.indeed.co.in/jobs?q=&l=Uttar+Pradesh",
                           "https://www.indeed.co.in/jobs?q=&l=Uttarakhand",
                           "https://www.indeed.co.in/jobs?q=&l=West+Bengal",
                           "https://www.indeed.co.in/jobs-in-Bangalore",
                           "https://www.indeed.co.in/jobs?q=&l=Delhi",
                           "https://www.indeed.co.in/jobs?q=&l=Mumbai%2C+Maharashtra",
                           "https://www.indeed.co.in/jobs?q=&l=Nagpur%2C+Maharashtra",
                           "https://www.indeed.co.in/jobs?q=&l=Siliguri%2C+West+Bengal",
                           "https://www.indeed.co.in/jobs?q=&l=Hyderabad%2C+Telangana",
                           "https://www.indeed.co.in/jobs?q=&l=Kolkata%2C+West+Bengal",
                           "https://www.indeed.co.in/jobs?q=&l=Chennai%2C+Tamil+Nadu"],
            "parsing_type": "xpath",
            'pagination': {
                'type': 'FOLLOW_LINKS',
                'next_page_criteria': {
                    'ext_codes': {
                        "parsing_type": "xpath",
                        "paths": ['.//link[@rel="next"]/@href'],
                        "cleanup_functions": ['"https://www.indeed.co.in"+obj.get("next_url")[key_i]'],
                        "return_type": 'str',
                    },
                },
            },
            "ext_codes": {
                "iterable": {
                    "parsing_type": "xpath",
                    "paths": ['.//div[@class="title"]/a'],
                    'return_type': 'list',
                },
                "job_url": {
                    "parsing_type": "xpath",
                    "selector": "iterable",
                    "paths": ['//a/@href'],
                    "cleanup_functions": ['"https://www.indeed.co.in"+obj.get("job_url")[key_i]'],
                    "return_type": 'str',
                    },
                "job_title": {
                    "parsing_type": "xpath",
                    "selector": "iterable",
                    "paths": ['//a/@title'],
                    "return_type": 'str',
                    },
                }
            },
        "job": {
            "parsing_type": "xpath",
            "start_urls": [
                "https://www.indeed.co.in/viewjob?jk=44fdcbab8eda2aba&tk=1disknkfj14fd000&from=serp&vjs=3&advn=5934745007518992&adid=294479825&sjdu=teYnAu8OgCGxABCwWD3OBGSvNPsXXaEnWLrUq8268_RHI32Q92bH_-Wq19zma82-wYoakt6dVdiQFqyTijcwVswsss5vEIkmnuv7gkJk_hUN1YT-MpOgf4iJknUR1_qHEx1h6fPHh2XDGattTLtqeG3MsUfEjnSx3m_weK-Z7j27aN3gVwClF75vIkyhYIBd-xvnSUe_3DuoKNeT1TmzsG_5YJHGfnWT75DmSe8a1MPYyJjtZ4IZ895xd8-3p9aC"
            ],
            "ext_codes": {
                "job_title": {
                    'paths': ['.//h3[contains(@class,"JobInfoHeader-title")]/text()'],
                    'return_type': 'str',
                },
                "job_description": {
                    'paths': ['.//div[@id="jobDescriptionText"]//text()'],
                    "join_str": " ",
                    'return_type': 'join',
                },
                "job_education_required": {
                    "paths": ['.//span[contains(text(),"Degrees:")]//text()',
                              './/p[contains(text(),"Degrees:")]//text()'],
                    "join_str": " ",
                    "return_type": "join",
                },
                "job_experience_required": {
                    'paths': ['.//span[contains(text(),"years experience")]/text()'],
                    'return_type': 'str',
                },
                "job_location": {
                    'paths': ['.//div[contains(@class,"--location")]/../span[contains(@class,"jobsearch")]/text()'],
                    'return_type': 'str',
                },
                "job_date_posted": {
                    "paths": ['.//b[contains(text(),"Job Posting")]/../text()'],
                    "return_type": "str",
                },
                "job_valid_through": {
                    "paths": ['.//p[contains(text(),"Last Date:")]/text()'],
                    "cleanup_functions": ['obj.get("job_valid_through")[key_i].replace("Last Date:","")'],
                    "return_type": "str",
                },
                "job_key": {
                    'paths': ['.//script[contains(text(),"jobKey")]/text()',
                              './/a[contains(@href,"SendToAFriend?jobId=")]/@href'],
                    "cleanup_functions": ['obj.get("job_key")[key_i].split("jobKey")[1].split(",")[0] if "jobKey" in obj.get("job_key")[key_i] else obj.get("job_key")[key_i].split("=")[-1]'],
                    'return_type': 'str',
                },
                "job_salary": {
                    'paths': ['.//p[contains(text(),"Salary:")]/text()',
                              './/p[contains(text(),"SALARY:")]/text()'],
                    "cleanup_functions": ['obj.get("job_salary")[key_i].replace("Salary:","")',
                                          'obj.get("job_salary")[key_i].replace("SALARY:","")'],
                    'return_type': 'str',
                },
                "job_type": {
                    "paths": ['.//p[contains(text(),"Job Type:")]/text()',
                              './/p[contains(text(),"Job Types:")]/text()',
                              './/b[contains(text(),"Schedule")]/../text()'],
                    "cleanup_functions": ['obj.get("job_type")[key_i].replace("Job Type:","")',
                                          'obj.get("job_type")[key_i].replace("Job Types:","")'],
                    "return_type": "str",
                },
                "job_industry_type": {
                    "cleanup_functions": ['obj.get("response").text.split("Industry:")[1].split("</p>")[0] if "<br/>Industry:" in obj.get("response").text else obj.get("response").text',
                                          'obj.get("response").split("<p>Industry:</p>")[1].split("</ul>")[0].replace("</li>",", ").replace("<li>","").replace("<ul>","") if "<p>Industry:</p>" in obj.get("response").text else obj.get("response")[key_i]'],
                    "join_str": " ",
                    "return_type": "join",
                },
                "job_profile": {
                    "paths": ['.//span[contains(text(),"Job Category:")]/text()'],
                    "cleanup_functions": ['obj.get("job_industry_type")[key_i].replace("Job Category:","").replace("&amp;","")'],
                    "return_type": "str",
                },
                "job_key_skills": {
                    "cleanup_functions": ['obj.get("response").text.split("Key Skills")[1].replace("<br/>","").split(">")[1].split("<")[0]'],
                    "return_type": "str",
                },
                "company_name": {
                    'paths': ['.//div[contains(@class,"jobsearch-InlineCompanyRating")]/div//text()'],
                    'return_type': 'str',
                },
                "company_url": {
                    "paths": ['.//div[contains(@class,"jobsearch-InlineCompanyRating")]/div/a/@href'],
                    "return_type": "str",
                },
                "company_rating": {
                    "paths": ['.//div[contains(@class,"Ratings")]/meta[@itemprop="ratingValue"]/@content'],
                    "return_type": "str",
                },
                "company_number_of_reviews": {
                    "paths": ['.//div[contains(@class,"Ratings")]/meta[@itemprop="ratingCount"]/@content'],
                    "return_type": "str",
                },
                "timestamp": {
                    "cleanup_functions": ['datetime.now().strftime("%Y-%m-%d")+" "+str(datetime.now().hour)+":"+str(datetime.now().minute)'],
                    "return_type": "str",
                },
            },
        },
    },

    "naukri_com": {
        "domain": "www.naukri.com",
        "method": "GET",
        "allowed_domains": ['naukri.com'],
        "parsing_type": "xpath",
        "sitemap": {
            "start_urls": ['file:///home/pankaj/Academics/Sem_9_restructured/MTP-I/employment_forecasting/efscrapper/efscrapper/efscrapper/sitemap_data/naukri/2019-08-24/sitemap-latest-jd-pages-2.xml',
                           'file:///home/pankaj/Academics/Sem_9_restructured/MTP-I/employment_forecasting/efscrapper/efscrapper/efscrapper/sitemap_data/naukri/2019-08-24/sitemap-latest-jd-pages-1.xml',
                           'file:///home/pankaj/Academics/Sem_9_restructured/MTP-I/employment_forecasting/efscrapper/efscrapper/efscrapper/sitemap_data/naukri/2019-08-24/sitemap-latest-jd-pages.xml',
                           'file:///home/pankaj/Academics/Sem_9_restructured/MTP-I/employment_forecasting/efscrapper/efscrapper/efscrapper/sitemap_data/naukri/2019-08-24/sitemap-expired-jd-pages-1.xml',
                           'file:///home/pankaj/Academics/Sem_9_restructured/MTP-I/employment_forecasting/efscrapper/efscrapper/efscrapper/sitemap_data/naukri/2019-08-24/sitemap-expired-jd-pages.xml'
                           ],
            "sitemap_rules": ['naukri.com'],
        },
        "category": {
            "start_urls": ["https://www.naukri.com/jobs-in-andhra-pradesh",
                           "https://www.naukri.com/jobs-in-arunachal-pradesh",
                           "https://www.naukri.com/jobs-in-assam",
                           "https://www.naukri.com/jobs-in-bihar",
                           "https://www.naukri.com/jobs-in-chhattisgarh",
                           "https://www.naukri.com/jobs-in-goa",
                           "https://www.naukri.com/jobs-in-gujarat",
                           "https://www.naukri.com/jobs-in-haryana",
                           "https://www.naukri.com/jobs-in-himachal-pradesh",
                           "https://www.naukri.com/jobs-in-jammu-and-kashmir",
                           "https://www.naukri.com/jobs-in-jharkhand",
                           "https://www.naukri.com/jobs-in-karnataka",
                           "https://www.naukri.com/jobs-in-kerala",
                           "https://www.naukri.com/jobs-in-madhya-pradesh",
                           "https://www.naukri.com/jobs-in-maharashtra",
                           "https://www.naukri.com/jobs-in-manipur",
                           "https://www.naukri.com/jobs-in-meghalaya",
                           "https://www.naukri.com/jobs-in-mizoram",
                           "https://www.naukri.com/jobs-in-nagaland",
                           "https://www.naukri.com/jobs-in-odisha",
                           "https://www.naukri.com/jobs-in-punjab",
                           "https://www.naukri.com/jobs-in-rajasthan",
                           "https://www.naukri.com/jobs-in-sikkim",
                           "https://www.naukri.com/jobs-in-tamil-nadu",
                           "https://www.naukri.com/jobs-in-telangana",
                           "https://www.naukri.com/jobs-in-tripura",
                           "https://www.naukri.com/jobs-in-uttar-pradesh",
                           "https://www.naukri.com/jobs-in-uttaranchal",
                           "https://www.naukri.com/jobs-in-west-bengal",
                           "https://www.naukri.com/jobs-in-chandigarh",
                           "https://www.naukri.com/jobs-in-mumbai",
                           "https://www.naukri.com/jobs-in-bangalore",
                           "https://www.naukri.com/jobs-in-chennai",
                           "https://www.naukri.com/jobs-in-delhi",
                           "https://www.naukri.com/jobs-in-hyderabad-secunderabad",
                           "https://www.naukri.com/jobs-in-kolkata",
                           "https://www.naukri.com/jobs-in-siliguri",
                           "https://www.naukri.com/jobs-in-nagpur"],
            "parsing_type": "xpath",
            'pagination': {
                'type': 'FOLLOW_LINKS',
                'next_page_criteria': {
                    'ext_codes': {
                        "parsing_type": "xpath",
                        "paths": ['.//link[@rel="next"]/@href'],
                        "return_type": 'str',
                    },
                },
            },
            "ext_codes": {
                "iterable": {
                    "parsing_type": "xpath",
                    "paths": ['.//a[@id="jdUrl"]'],
                    'return_type': 'list',
                },
                "job_url": {
                    "parsing_type": "xpath",
                    "selector": "iterable",
                    "paths": ['//a/@href'],
                    "return_type": 'str',
                    },
                "job_title": {
                    "parsing_type": "xpath",
                    "selector": "iterable",
                    "paths": ['//a/text()'],
                    "return_type": 'str',
                    },
                }
            },
        "job": {
            "parsing_type": "xpath",
            "start_urls": [
                "https://www.naukri.com/job-listings-Advisor-Data-Intelligence-Engineer-Dell-International-Services-India-Private-Limited-Bengaluru-5-to-7-years-010819908361?src=jobsearchDesk&sid=15656826262775&xp=1&px=1"
            ],
            "ext_codes": {
                "job_title": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()',
                              './/h1[@itemprop="headline"]/text()',
                              './/h1[@title="jobTitleHeading"]/text()',
                              './/td[contains(text(),"Designation")]/../td[@class="detailJob"]/text()'],
                    'cleanup_functions': ['obj.get("job_title")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_title")[key_i])["title"]',
                                          'obj.get("job_title")[key_i].split(" - ")[0]'],
                    'return_type': 'str',
                },
                "job_description": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()',
                              './/div[@class="clearboth description"]//text()',
                              './/h2[@class="jobDescriptionHeading "]/../..//text()',
                              './/td[contains(text(),"Job Description")]/../td[@class="detailJob"]/text()'],
                    'cleanup_functions': ['obj.get("job_description")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_description")[key_i])["description"]'],
                    "join_str": " ",
                    'return_type': 'join',
                },
                "job_experience_required": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()',
                              './/span[contains(@class,"meta-exp")]/text()',
                              './/span[@class="icon exp"]/../text()',
                              './/td[contains(text(),"Experience")]/../td[@class="detailJob"]/text()'],
                    'cleanup_functions': ['obj.get("job_experience_required")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_experience_required")[key_i])["experienceRequirements"]'],
                    'return_type': 'str',
                },
                "job_education_required": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()',
                              './/p[contains(text(),"Education")]/../p[@class="coPE"]/span[@itemprop=""]/text()',
                              './/div[contains(text(),"Education:")]/text()',
                              './/td[contains(text(),"Education")]/../td[@class="detailJob"]/text()'],
                    'cleanup_functions': ['obj.get("job_education_required")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_education_required")[key_i])["educationRequirements"]'],
                    "join_str": " ",
                    "return_type": "join",
                },
                "job_location": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()',
                              './/span[@class="jobs-icon loc"]/../text()',
                              './/span[@class="icon loc"]/..//a/text()',
                              './/td[contains(text(),"Location")]/..//span[@class="city"]/text()'],
                    'cleanup_functions': ['obj.get("job_location")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_location")[key_i])["jobLocation"]["address"]["streetAddress"]'],
                    'return_type': 'str',
                },
                "job_date_posted": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()',
                              './/span[contains(text(),"Posted:")]/strong/text()',
                              './/span[contains(text(),"Posted:")]/text()',
                              './/td[contains(text(),"Job Posted")]/../td[@class="detailJob"]/text()'],
                    'cleanup_functions': ['obj.get("job_date_posted")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_date_posted")[key_i])["datePosted"]'],
                    'return_type': 'str',
                },
                "job_valid_through": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()'],
                    'cleanup_functions': ['obj.get("job_valid_through")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_valid_through")[key_i])["validThrough"]'],
                    'return_type': 'str',
                },
                "job_key": {
                    'paths': ['.//script[contains(text(),"contactDetails?file")]/text()',
                              './/input[@id="login_jobID"]/@value'],
                    "cleanup_functions": ['re.findall("\d+",obj.get("job_key")[key_i].split("jobId")[1])[0]'],
                    'return_type': 'str',
                },
                "similar_job_keys": {
                    'paths': ['.//script[contains(text(),"contactDetails?file")]/text()'],
                    "cleanup_functions": ['", ".join(re.findall("\d+",obj.get("similar_job_keys")[key_i].split("simJobIds")[1].split(";")[0]))'],
                    'return_type': 'str',
                },
                "job_work_hour": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()'],
                    'cleanup_functions': ['obj.get("job_work_hour")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_work_hour")[key_i])["workHours"]'],
                    'return_type': 'str',
                },
                "job_salary": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()',
                              './/span[contains(@class,"meta-sal")]/text()',
                              './/span[@class="icon rup"]/../text()',
                              './/td[contains(text(),"Compensation:")]/../td[@class="detailJob"]/text()'],
                    'cleanup_functions': ['obj.get("job_salary")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_salary")[key_i])["baseSalary"]["value"]["value"]'],
                    'return_type': 'str',
                },
                "job_type": {
                    "paths": ['.//script[contains(text(),"experienceRequirements")]/text()',
                              './/em[contains(text(),"Employment Type:")]/../span/text()',
                              './/td[contains(text(),"Employment Type")]/../td[@class="detailJob"]/text()'],
                    'cleanup_functions': ['obj.get("job_type")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_type")[key_i])["employmentType"]',
                                          'obj.get("job_type")[key_i].text.split("Employment Type:")[1].split("<br/>")[0]'],
                    "return_type": "str",
                },
                "job_industry_type": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()',
                              './/em[contains(text(),"Industry:")]/..//span/text()',
                              './/em[contains(text(),"Industry:")]/../span/a/text()',
                              './/em[contains(text(),"Functional Area:")]/../span/a/text()',
                              './/em[contains(text(),"Role Category:")]/..//span/text()',
                              './/em[contains(text(),"Role:")]/..//span/text()',
                              './/h2[@class="jobDescriptionHeading "]/../..//a[contains(@title,"Find all jobs matching")]/span/text()',
                              './/td[contains(text(),"Industry Type")]/../td[@class="detailJob"]/text()'],
                    'cleanup_functions': ['obj.get("job_industry_type")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_industry_type")[key_i])["industry"]'],
                    "join_str": ", ",
                    "return_type": "join",
                },
                "job_profile": {
                    "paths": ['.//em[contains(text(),"Role:")]/..//span/text()'],
                    "return_type": "str",
                },
                "job_key_skills": {
                    "paths": ['.//div[@class="ksTags"]//text()',
                              './/div[@class="tagcloud"]//span/text()',
                              './/a[@class="tag"]/span/text()'],
                    "join_str": ", ",
                    "return_type": "join",
                },
                "job_views": {
                    'paths': ['.//span[contains(text(),"Job Views:")]/strong/text()'],
                    "return_type": "str",
                },
                "job_applicants": {
                    'paths': ['.//span[contains(text(),"Job Applicants:")]/strong/text()'],
                    "return_type": "str",
                },
                "job_openings": {
                    'paths': ['.//span[contains(text(),"Openings:")]/strong/text()',
                              './/td[contains(text(),"Designation")]/../td[@class="detailJob"]/text()'],
                    "cleanup_functions": ['obj.get("job_openings")[key_i].split(" - ")[1].replace("Opening(s)","")'],
                    "return_type": "str",
                },
                "company_name": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()',
                              './/p[@itemprop="name"]/text()',
                              './/div[contains(text(),"PVT. LTD")]/text()',
                              './/td[contains(text(),"Contact")]/../td[@class="detailJob"]/text()'],
                    'cleanup_functions': ['obj.get("company_name")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("company_name")[key_i])["hiringOrganization"]["name"]'],
                    "join_str": ", ",
                    'return_type': 'join',
                },
                "about_company": {
                    "paths": ['.//h4[@class="jobCompanyProfileHeading"]/../..//text()',
                              './/div[@class="discp"]/text()',
                              '(.//table[@class="jobsTable"]/tr/td[@class="detailJob"])[1]/text()'],
                    "join_str": " ",
                    "return_type": "join",
                },
                "company_rating": {
                    "paths": ['.//span[@class="rating"]/text()'],
                    "return_type": "str",
                },
                "company_number_of_reviews": {
                    "paths": ['.//span[@class="review"]/text()'],
                    "cleanup_functions": ['obj.get("company_number_of_reviews")[key_i].replace("reviews)","")',
                                          'obj.get("company_number_of_reviews")[key_i].replace("(","")'],
                    "return_type": "str",
                },
                "company_url": {
                    "paths": ['.//a[@itemprop="hiringOrganization"]/@href'],
                    "cleanup_functions": ['"https://www.naukri.com/"+obj.get("company_url")[key_i]'],
                    "return_type": "str",
                },
                "contact_person_name": {
                    "paths": ['.//span[@id="favId"]/@jid',
                              './/td[contains(text(),"Contact")]/../td[@class="detailJob"]/text()[1]'],
                    "cleanup_functions": ['"https://www.naukri.com/jd/contactDetails?file="+obj.get("contact_person_name")[key_i]',
                                          'requests.get(obj.get("contact_person_name")[key_i], headers=self.headers).text',
                                          'obj.get("contact_person_name")[key_i].split("fields")[1].split("sendQueryForm")[0]',
                                          '",".join(obj.get("contact_person_name")[key_i].split(",")[:-1])',
                                          '":".join(obj.get("contact_person_name")[key_i].split(":")[1:])',
                                          'json.loads(obj.get("contact_person_name")[key_i])["Recruiter Name"]',
                                          'np.nan if "{" in obj.get("contact_person_name")[key_i] else obj.get("contact_person_name")[key_i]'],
                    "return_type": "str",
                },
                "contact_person_email": {
                    "paths": ['.//span[@id="favId"]/@jid'],
                    "cleanup_functions": ['"https://www.naukri.com/jd/contactDetails?file="+obj.get("contact_person_email")[key_i]',
                                          'requests.get(obj.get("contact_person_email")[key_i], headers=self.headers).text',
                                          'obj.get("contact_person_email")[key_i].split("fields")[1].split("sendQueryForm")[0]',
                                          '",".join(obj.get("contact_person_email")[key_i].split(",")[:-1])',
                                          '":".join(obj.get("contact_person_email")[key_i].split(":")[1:])',
                                          'json.loads(obj.get("contact_person_email")[key_i])["Email Address"]["title"]',
                                          'np.nan if "{" in obj.get("contact_person_email")[key_i] else obj.get("contact_person_email")[key_i]'],
                    "return_type": "str",
                },
                "contact_person_number": {
                    "paths": ['.//span[@id="favId"]/@jid',
                              './/td[contains(text(),"Telephone")]/../td[@class="detailJob"]/text()'],
                    "cleanup_functions": ['"https://www.naukri.com/jd/contactDetails?file="+obj.get("contact_person_number")[key_i]',
                                          'requests.get(obj.get("contact_person_number")[key_i], headers=self.headers).text',
                                          'obj.get("contact_person_number")[key_i].split("fields")[1].split("sendQueryForm")[0]',
                                          '",".join(obj.get("contact_person_number")[key_i].split(",")[:-1])',
                                          '":".join(obj.get("contact_person_number")[key_i].split(":")[1:])',
                                          'json.loads(obj.get("contact_person_number")[key_i])["Telephone"]',
                                          'np.nan if "{" in obj.get("contact_person_number")[key_i] else obj.get("contact_person_number")[key_i]'],
                    "return_type": "str",
                },
                "timestamp": {
                    "cleanup_functions": ['datetime.now().strftime("%Y-%m-%d")+" "+str(datetime.now().hour)+":"+str(datetime.now().minute)'],
                    "return_type": "str",
                },
            },
        },
    },

    "timesjobs_com": {
        "domain": "www.timesjobs.com",
        "method": "GET",
        "allowed_domains": ['timesjobs.com'],
        "parsing_type": "xpath",
        "category": {
            "start_urls": ["https://www.timesjobs.com/candidate/job-search.html?searchType=personalizedSearch&from=submit&txtKeywords=&txtLocation=India"],
            "parsing_type": "xpath",
            'pagination': {
                'type': 'FOLLOW_LINKS',
                'next_page_criteria': {
                    'ext_codes': {
                        "parsing_type": "xpath",
                        "paths": ['.//link[@rel="next"]/@href'],
                        "return_type": 'str',
                    },
                },
            },
            "ext_codes": {
                "iterable": {
                    "parsing_type": "xpath",
                    "paths": ['.//h3[@class="joblist-comp-name"]/../h2/a'],
                    'return_type': 'list',
                },
                "job_url": {
                    "parsing_type": "xpath",
                    "selector": "iterable",
                    "paths": ['//a/@href'],
                    "return_type": 'str',
                    },
                "job_title": {
                    "parsing_type": "xpath",
                    "selector": "iterable",
                    "paths": ['//a/text()'],
                    "return_type": 'str',
                    },
                }
            },
        "job": {
            "parsing_type": "xpath",
            "start_urls": [
                "https://www.timesjobs.com/job-detail/video-editor-k4-infotech-pvt-ltd-noida-greater-noida-0-3yrs-jobid-TcQtHTRxWQVzpSvf__PLUS__uAgZw==-loc-198325&source=srp"
            ],
            "ext_codes": {
                "job_title": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()'],
                    'cleanup_functions': ['obj.get("job_title")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_title")[key_i])["title"]'],
                    'return_type': 'str',
                },
                "job_description": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()'],
                    'cleanup_functions': ['obj.get("job_description")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_description")[key_i])["description"]'],
                    'return_type': 'str',
                },
                "job_experience_required": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()'],
                    'cleanup_functions': ['obj.get("job_experience_required")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_experience_required")[key_i])["experienceRequirements"]'],
                    'return_type': 'str',
                },
                "job_education_required": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()'],
                    'cleanup_functions': ['obj.get("job_education_required")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_education_required")[key_i])["educationRequirements"]'],
                    "return_type": "str",
                },
                "job_location": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()',
                              './/i[contains(text(),"location_on")]/../text()'],
                    'cleanup_functions': ['obj.get("job_location")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_location")[key_i])["jobLocation"]["address"]["addressLocality"]',
                                          '",".join([temp_i["address"]["addressLocality"] for temp_i in json.loads(obj.get("job_location")[key_i])["jobLocation"]])'],
                    'return_type': 'str',
                },
                "job_date_posted": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()'],
                    'cleanup_functions': ['obj.get("job_date_posted")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_date_posted")[key_i])["datePosted"]'],
                    'return_type': 'str',
                },
                "job_valid_through": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()'],
                    'cleanup_functions': ['obj.get("job_valid_through")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_valid_through")[key_i])["validThrough"]'],
                    'return_type': 'str',
                },
                "job_key": {
                    'paths': ['.//div[@class="jd-jobid"]/text()'],
                    "cleanup_functions": ['obj.get("job_key")[key_i].replace("Job Id: ","")'],
                    'return_type': 'str',
                },
                "similar_job_keys": {
                    'paths': ['.//script[contains(text(),"getJdsimilarjobs.json")]/text()'],
                    "cleanup_functions": ['obj.get("similar_job_keys")[key_i].split("adId=")[1].split("&")[0]+"&source="+obj.get("similar_job_keys")[key_i].split("source=")[2].split("&")[0]',
                                          '"https://www.timesjobs.com/candidate/getJdsimilarjobs.json?adId="+obj.get("similar_job_keys")[key_i]',
                                          'requests.get(obj.get("similar_job_keys")[key_i], headers=self.headers)',
                                          '[] if "No Similar Jobs found" in obj.get("similar_job_keys")[key_i] else json.loads(obj.get("similar_job_keys")[key_i].text)["similarJobsList"]',
                                          '[temp_i["adId"] for temp_i in obj.get("similar_job_keys")[key_i]]'],
                    "join_str": ", ",
                    'return_type': 'join',
                },
                "job_salary": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()'],
                    'cleanup_functions': ['obj.get("job_salary")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_salary")[key_i])["baseSalary"]["value"]["value"]'],
                    'return_type': 'str',
                },
                "job_type": {
                    "paths": ['.//script[contains(text(),"experienceRequirements")]/text()'],
                    'cleanup_functions': ['obj.get("job_type")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_type")[key_i])["employmentType"]'],
                    "return_type": "str",
                },
                "job_industry_type": {
                    "paths": ['.//label[contains(text(),"Industry")]/../span/text()',
                              './/label[contains(text(),"Job Function:")]/../span/text()'],
                    "join_str": ", ",
                    "return_type": "join",
                },
                "job_profile": {
                    "paths": ['.//label[contains(text(),"Role:")]/../span/text()'],
                    "return_type": "str",
                },
                "job_key_skills": {
                    "paths": ['.//script[contains(text(),"experienceRequirements")]/text()'],
                    'cleanup_functions': ['obj.get("job_key_skills")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("job_key_skills")[key_i])["skills"]'],
                    "return_type": "str",
                },
                "company_name": {
                    'paths': ['.//script[contains(text(),"experienceRequirements")]/text()'],
                    'cleanup_functions': ['obj.get("company_name")[key_i].replace("\t"," ").replace("\n"," ")',
                                          'json.loads(obj.get("company_name")[key_i])["hiringOrganization"]'],
                    'return_type': 'str',
                },
                "company_website": {
                    "paths": ['.//label[contains(text(),"Website")]/..//a/@href'],
                    "return_type": "str",
                },
                "company_turn_over": {
                    "paths": ['.//label[contains(text(),"Company Turnover")]/../span/text()'],
                    "return_type": "str",
                },
                "company_size": {
                    "paths": ['.//label[contains(text(),"Company Size")]/../span/text()'],
                    "return_type": "str",
                },
                "timestamp": {
                    "cleanup_functions": ['datetime.now().strftime("%Y-%m-%d")+" "+str(datetime.now().hour)+":"+str(datetime.now().minute)'],
                    "return_type": "str",
                },
            },
        },
    },

    "monsterindia_com": {
        "domain": "www.monsterindia.com",
        "method": "GET",
        "allowed_domains": ['monsterindia.com'],
        "parsing_type": "xpath",
        "sitemap": {
            "start_urls": ['https://www.monsterindia.com/xmlsitemap/active-jobs-sitemap0.xml',
                           'https://www.monsterindia.com/xmlsitemap/active-jobs-sitemap1.xml',
                           'https://www.monsterindia.com/xmlsitemap/active-jobs-sitemap2.xml',
                           'https://www.monsterindia.com/xmlsitemap/active-jobs-sitemap3.xml',
                           'https://www.monsterindia.com/xmlsitemap/expired-jobs-sitemap0.xml',
                           'https://www.monsterindia.com/xmlsitemap/todays-jobs-sitemap.xml'
                           ],
            "sitemap_rules": ['/job/'],
        },
        # "job": {
        #     "start_urls": [
        #         'https://www.monsterindia.com/job-vacancy-hopeline-placement-jewellery-diamond-assorting-and-bagging-hopeline-placement-mumbai-mumbai-city-2-8-years-23875670.html',
        #     ],
        #     "parsing_type": "xpath",
        #     "ext_codes": {
        #         "job_title": {
        #             'paths': ['.//script[contains(text(),"hiringOrganization")]/text()',
        #                       './/h1[@itemprop="title"]/text()',
        #                       './/title/text()'],
        #             'cleanup_functions': ['obj.get("title")[key_i].replace("\t"," ").replace("\n"," ")',
        #                                   'json.loads(obj.get("job_title")[key_i])["title"]'],
        #             'return_type': 'str',
        #         },
        #         "job_description": {
        #             'paths': ['.//script[contains(text(),"hiringOrganization")]/text()',
        #                       './/div[@class="job_description "]//div[@class="desc"]//text()',
        #                       './/div[@class="info"]/p/text()'],
        #             'cleanup_functions': ['obj.get("job_description")[key_i].replace("\t"," ").replace("\n"," ")',
        #                                   'json.loads(obj.get("job_description")[key_i])["description"]'],
        #             'return_type': 'join',
        #         },
        #         "job_experience_required": {
        #             "paths": ['.//div[@class="joblnk"]/div[contains(text()," years")]/text()',
        #                       './/td[contains(text(),"Years of Experience")]/text()'],
        #             "return_type": "str",
        #         },
        #         "job_education_required": {
        #             # "paths": ['.//div[contains(text(),"Education")]/../span/a/text()'],
        #             "cleanup_functions": ['obj.get("job_education_required")[key_i].split("Eligibility")[1].split("<br>")[0]',
        #                                   'obj.get("job_education_required")[key_i].split("Education</div>")[1].split("</span>")[0]+"</span>"',
        #                                   '"" if "</html>" in obj.get("job_education_required")[key_i] else obj.get("job_education_required")[key_i]',
        #                                   'HtmlResponse(url="temp string", body=obj.get("job_education_required")[key_i],encoding="utf-8")',
        #                                   '",".join(obj.get("job_education_required")[key_i].xpath(".//text()").extract())'
        #                                   ],
        #             "return_type": "str",
        #         },
        #         "job_location": {
        #             'paths': ['.//script[contains(text(),"hiringOrganization")]/text()',
        #                       './/option[contains(text(),"Current location")]/../option[2]/text()',
        #                       './/td[contains(text(),"Location")]/text()'],
        #             'cleanup_functions': ['obj.get("job_location")[key_i].replace("\t"," ").replace("\n"," ")',
        #                                   'json.loads(obj.get("job_location")[key_i])["jobLocation"]["address"]["addressLocality"]',
        #                                   '[temp_i["address"]["addressLocality"] for temp_i in json.loads(obj.get("job_location")[key_i])["jobLocation"]]'],
        #             'return_type': 'join',
        #         },
        #         "job_date_posted": {
        #             'paths': ['.//script[contains(text(),"hiringOrganization")]/text()',
        #                       './/div[contains(text(),"Posted:")]/span/text()',
        #                       './/td[contains(text(),"Posted On")]/text()'],
        #             'cleanup_functions': ['obj.get("job_date_posted")[key_i].replace("\t"," ").replace("\n"," ")',
        #                                   'json.loads(obj.get("job_date_posted")[key_i])["datePosted"]'],
        #             'return_type': 'str',
        #         },
        #         "job_salary": {
        #             "paths": ['.//div[contains(text(),"Salary")]/text()'],
        #             "return_type": "str",
        #         },
        #         "job_type": {
        #             "paths": ['.//script[contains(text(),"hiringOrganization")]/text()'],
        #             "cleanup_functions": ['obj.get("job_type")[key_i].replace("\t"," ").replace("\n"," ")',
        #                                   'json.loads(obj.get("job_type")[key_i])["employmentType"]'],
        #             "return_type": 'str',
        #         },
        #         "job_industry_type": {
        #             "cleanup_functions": ['obj.get("job_industry_type")[key_i].split("<td>Function<br />")[1].split("</td>")[0]',
        #                                   'obj.get("job_industry_type")[key_i].split("Function</div>")[1].split("</span>")[0]+"</span>"',
        #                                   'HtmlResponse(url="temp string",body=obj.get("job_industry_type")[key_i],encoding="utf-8")',
        #                                   '",".join(obj.get("job_industry_type")[key_i].xpath(".//text()").extract())'],
        #             "return_type": "str",
        #         },
        #         "job_key_skills": {
        #             "paths": ['.//h2[@class="keyskill skillseotag"]/text()',
        #                       './/td[contains(text(),"Skills")]/text()'],
        #             "return_type": "str",
        #         },
        #         "company_name": {
        #             "paths": ['.//a[@class="company"]/text()',
        #                       './/script[contains(text(),"hiringOrganization")]/text()',
        #                       './/td[contains(text(),"Company")]/strong/text()'],
        #             "cleanup_functions": ['obj.get("company_name")[key_i].replace("\t"," ").replace("\n"," ")',
        #                                   'json.loads(obj.get("company_name")[key_i])["hiringOrganization"]["name"]'],
        #             "return_type": "str",
        #         },
        #         "company_url": {
        #             "paths": ['.//a[contains(@href,"company.monsterindia")]/@href',
        #                       './/a[@class="company"]/@href'],
        #             "cleanup_functions": ['"https:"+obj.get("company_url")[key_i]'],
        #             "return_type": "str",
        #         },
        #         "company_website": {
        #             "paths": ['.//a[@class="link"]/@href'],
        #             "return_type": "str",
        #         },
        #         "about_company": {
        #             "paths": ['.//h3[contains(text(),"About Company")]/../div[@class="desc"]/text()',
        #                       './/span[contains(text(),"About ")]/../../../p//text()'],
        #             "return_type": "join",
        #         },
        #         "job_key": {
        #             "paths": ['.//script[contains(text(),"actual jobid here")]/text()',
        #                       './/a[contains(text(),"APPLY NOW")]/@href'],
        #             'cleanup_functions': ['obj.get("job_key")[key_i].split("jobid")[1]',
        #                                   're.findall("\d+",obj.get("job_key")[key_i])[0]',
        #                                   'obj.get("job_key")[key_i].split("job=")[-1].split("&")[0]'],
        #             'return_type': 'str',
        #         },
        #         "similar_job_keys": {
        #             "paths": ['.//ul[@class="ullilist"]//div[@class="jtitle"]/../@href'],
        #             'cleanup_functions': ['obj.get("similar_job_keys")[key_i].split("-")[-1].split(".")[0]'],
        #             'return_type': "join",
        #         },
        #         "timestamp": {
        #             "cleanup_functions": ['datetime.now().strftime("%Y-%m-%d")+" "+str(datetime.now().hour)+":"+str(datetime.now().minute)'],
        #             "return_type": "str",
        #         },
        #     },
        # },
        "job": {
            "parsing_type": "jpath",
            "ext_codes": {
                "job_title": {
                    "paths": ['["jobDetailResponse"]["title"]'],
                    "return_type": "str",
                },
                "job_description": {
                    "paths": ['["jobDetailResponse"]["description"]'],
                    "return_type": "str",
                },
                "job_experience_required": {
                    "paths": ['["jobDetailResponse"]["minimumExperience"]["years"]',
                              '["jobDetailResponse"]["maximumExperience"]["years"]'],
                    "join_str": " - ",
                    "return_type": "join",
                },
                "job_location": {
                    "paths": ['["jobDetailResponse"]["locations"]'],
                    "cleanup_functions": ['obj.get("job_location")[key_i]["city"]'],
                    "join_str": ", ",
                    "return_type": "join",
                },
                "job_date_posted": {
                    "paths": ['["jobDetailResponse"]["postedAt"]'],
                    "cleanup_functions": ['datetime.now().strftime("%Y-%m-%d") if "day ago" in obj.get("job_date_posted")[key_i] or "hours ago" in obj.get("job_date_posted")[key_i] else obj.get("job_date_posted")[key_i]'],
                    "return_type": "str",
                },
                "job_valid_through": {
                    "paths": ['["jobDetailResponse"]["closedAt"]'],
                    "cleanup_functions": ['np.nan if obj.get("job_valid_through")[key_i] == 0 else obj.get("job_valid_through")[key_i]'],
                    "return_type": "str",
                },
                "job_key": {
                    "paths": ['["jobDetailResponse"]["jobId"]'],
                    "return_type": "str",
                },
                "similar_job_keys": {
                    "paths": ['["jobDetailResponse"]["similarJobs"]["data"]'],
                    "cleanup_functions": ['obj.get("similar_job_keys")[key_i]["jobId"]'],
                    "join_str": ", ",
                    "return_type": "join",
                },
                "job_salary": {
                    "paths": ['["jobDetailResponse"]["salary"]'],
                    "return_type": "str",
                },
                "job_type": {
                    "paths": ['["jobDetailResponse"]["employmentTypes"]'],
                    "join_str": ", ",
                    "return_type": "join",
                },
                "job_industry_type": {
                    "paths": ['["jobDetailResponse"]["industries"]',
                              '["jobDetailResponse"]["functions"]'],
                    "join_str": ", ",
                    "return_type": "join",
                },
                "job_profile": {
                    "paths": ['["jobDetailResponse"]["roles"]'],
                    "join_str": ", ",
                    "return_type": "join",
                },
                "job_key_skills": {
                    "paths": ['["jobDetailResponse"]["itSkills"]',
                              '["jobDetailResponse"]["skills"]'],
                    "cleanup_functions": ['obj.get("job_key_skills")[key_i]["text"]'],
                    "join_str": ", ",
                    "return_type": "join",
                },
                "job_applicants": {
                    "paths": ['["jobDetailResponse"]["totalApplicants"]'],
                    "return_type": "str",
                },
                "company_name": {
                    "paths": ['["jobDetailResponse"]["companyName"]'],
                    "return_type": "str",
                },
                "about_company": {
                    "paths": ['["jobDetailResponse"]["company"]["about"]'],
                    "return_type": "str",
                },
                "company_url": {
                    "paths": ['["jobDetailResponse"]["company"]'],
                    "cleanup_functions": [
                                          'obj.get("company_url")[key_i]["name"].replace(" ","-")+"-"+obj.get("company_url")[key_i]["id"]',
                                          '"https://www.monsterindia.com/search/"+obj.get("company_url")[key_i] + "-jobs-career"'],
                    "return_type": "str",
                },
                "contact_person_name": {
                    "paths": ['["jobDetailResponse"]["recruiterName"]'],
                    "return_type": "str",
                },
                "contact_person_email": {
                    "paths": ['["jobDetailResponse"]["recruiter"]["email"]'],
                    "return_type": "str",
                },
                "contact_person_number": {
                    "paths": ['["jobDetailResponse"]["recruiterContactNumber"]'],
                    "return_type": "str",
                },
                "timestamp": {
                    "cleanup_functions": ['datetime.now().strftime("%Y-%m-%d")+" "+str(datetime.now().hour)+":"+str(datetime.now().minute)'],
                    "return_type": "str",
                },
            },
        },
    },

    "jobsarkari_com": {
        "domain": "www.jobsarkari.com",
    },
}

print("**********************************************************")
print("Total websites added: ", len(list(site_config.keys())))
print("------------------")